Ramon 2404
tue-ees-5xwg0/power-system-simulation-acdc pull request #34
Opened 2024-06-14 11:13 UTC by Ramonpwb

- Added N-1
- Created test file
- Created N-1 test case
- Untangled all the code

2024-06-14 13:35 UTC, ACMason117 requested changes
If you could fix that one part your code overwrote please

2024-06-14 13:35 UTC, ACMason117 commented on src/power_system_simulation/power_flow_processing.py
Are the 2 lines supposed to be removed?

2024-06-14 13:35 UTC, ACMason117 commented on src/power_system_simulation/power_system_simulation.py
You removed some of my code, can you add these back?

Not the 'trek een bak part'

2024-06-14 13:52 UTC, ACMason117 approved these changes

2024-06-16 13:35 UTC, ACMason117 approved these changes

2024-06-16 14:58 UTC, MakiVr approved these changes

2024-06-16 15:12 UTC, merged